---
# cloudflared default variables
cloudflared_dir: "/opt/cloudflared"
cloudflared_gpg_key_url: "https://pkg.cloudflare.com/cloudflare-main.gpg"
cloudflared_apt_repository: "deb [signed-by=/etc/apt/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_facts['distribution_release'] }} main"
